default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  username: <%= ENV.fetch("DB_USERNAME", "baseline") %>
  password: <%= ENV.fetch("DB_PASSWORD", "baseline") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: baseline_micropost_development

test:
  <<: *default
  database: baseline_micropost_test

production:
  <<: *default
  database: baseline_micropost_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
